version: '3.3'

services:
   db:
     image: mysql
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
     ports:
       - "3306:3308"
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: mysql
       MYSQL_USER: root
       MYSQL_PASSWORD: root

volumes:
    dbdata:
